language: python

# newer python versions are available only on xenial
# (while some older only on trusty) Ubuntu distribution
dist: xenial
sudo: required

branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Build master too
    - master

matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8

install:
  - python -m pip install --upgrade pip
  - pip install coverage
  - pip install coveralls
  - pip install git+https://github.com/pyvisa/pyvisa.git#egg=pyvisa
  - pip install pytest pytest-cov

script:
  - pip install -e .
  - pytest pyvisa-py/testsuite --cov pyvisa-py --cov-report xml

after_script:
  - coveralls --verbose
